# Generated by Django 5.1.3 on 2024-12-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_4_all', '0002_customer_latitude_customer_longitude_order_saveditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='experience',
        ),
    ]
